version: "3.8"
services:
    client:
        build: ./client
        container_name: emc-client
        ports:
            - 8080:8080
        develop:
            watch:
                - action: sync
                  path: ./client
                  target: /client
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ./client/package.json
    auth:
        build: ./auth
        container_name: emc-auth
        ports:
            - 4000:4000
        env_file:
            - path: ./auth/.env
              required: true
        develop:
            watch:
                - action: sync
                  path: ./auth
                  target: /auth
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./auth/package.json
