version: "3.8"
services:
    client:
        build: ./client
        container_name: emc-client
        ports:
            - 8080:8080
        develop:
            watch:
                - action: sync
                  path: ./client
                  target: /client
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ./client/package.json
    auth:
        build: ./auth
        container_name: emc-auth
        depends_on:
            - db-user
        ports:
            - 4000:4000
        env_file:
            - path: ./auth/.env
              required: true
        environment:
            DB_URL: mongodb://root:example@db-user:27017
        develop:
            watch:
                - action: sync
                  path: ./auth
                  target: /auth
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./auth/package.json
    user:
        build: ./user
        container_name: emc-user
        depends_on:
            - db-user
        ports:
            - 4001:4001
        env_file:
            - path: ./user/.env
              required: true
        environment:
            DB_URL: mongodb://root:example@db-user:27017
        develop:
            watch:
                - action: sync
                  path: ./user
                  target: /user
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./user/package.json
    product:
        build: ./product
        container_name: emc-product
        depends_on:
            - db-product
        ports:
            - 4002:4002
        env_file:
            - path: ./product/.env
              required: true
        environment:
            DB_URL: mongodb://root:example@db-product:27017
        develop:
            watch:
                - action: sync
                  path: ./product
                  target: /product
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./product/package.json
    cart:
        build: ./cart
        container_name: emc-cart
        depends_on:
            - db-cart
        ports:
            - 4003:4003
        env_file:
            - path: ./cart/.env
              required: true
        environment:
            DB_URL: mongodb://root:example@db-cart:27017
        develop:
            watch:
                - action: sync
                  path: ./cart
                  target: /cart
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./cart/package.json
    db-user:
        build: ./db-user
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - db_user:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    db-product:
        build: ./db-product
        image: mongo
        restart: always
        ports:
            - 27018:27017
        volumes:
            - db_product:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    db-cart:
        build: ./db-cart
        image: mongo
        restart: always
        ports:
            - 27019:27017
        volumes:
            - db_cart:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

volumes:
    db_user:
        name: db_user_data
    db_product:
        name: db_product_data
    db_cart:
        name: db_cart_data
