version: "3.8"
services:
    client:
        build: ./client
        container_name: emc-client
        ports:
            - 8080:8080
        develop:
            watch:
                - action: sync
                  path: ./client
                  target: /client
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ./client/package.json
    auth:
        build: ./auth
        container_name: emc-auth
        depends_on:
            - db-user
        ports:
            - 4000:4000
        env_file:
            - path: ./auth/.env
              required: true
        environment:
            DB_URL: mongodb://root:example@db-user:27017
        develop:
            watch:
                - action: sync
                  path: ./auth
                  target: /auth
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./auth/package.json
    user:
        build: ./user
        container_name: emc-user
        depends_on:
            - db-user
        ports:
            - 4001:4001
        env_file:
            - path: ./user/.env
              required: true
        environment:
            DB_URL: mongodb://root:example@db-user:27017
        develop:
            watch:
                - action: sync
                  path: ./user
                  target: /user
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./user/package.json
    db-user:
        build: ./db-user
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - db_user:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

volumes:
    db_user: {}
